input_path = "" # Ex: 'C:/Users/.../Music/'
output_path = "" # Ex: 'C:/Users/.../Music/432/'
min_rating = 0
vel = 432 / 440
overwrite = False
append = " (432hz)"
just_copy = "432hz"
filetype = ".mp3"
maxthreads = 16
