input_path = "" # Ex: 'C:/Users/.../Music/'
output_path = "" # Ex: 'C:/Users/.../Music/432/'
min_rating = 0 # Limits tracks of the input folder to the minimum rating
vel = 432 / 440 # Ratio to process the tracks with, single numbers work as well, ex: 0.9818
overwrite = False # Overwrites all tracks in the output folder which have the same filename
remove_remnants = False # Removes all tracks in the output folder that don't meet the new criteria
maxthreads = 16 # Maximum amount of threads, useful for keeping memory usage low but can exceed your CPU's thread count
append = " (432hz)" # Addendum for the filenames of the new files
just_copy = "432hz" # Criteria the filename has to meet for files that are already 432hz
filetype = ".mp3" # Mp3 works, other file types haven't been tested yet
